# SECURITY
jwt:
  secret:
    key: jihoonZ2LUB5HMOe9Lt3jSwnhYK61UiDW8nK9Fm7mn6VQHj9lzunksfsb2NoUAHOED2uwvstNSpMY6Xits7i6iYdlK5iCLFMAW1qDjDANTBey9hW7VQtk1eoXBfNEIQYAz4pRGisarSeVEF5x9uBt9QFSDRFon44jirdjh0fX70eI72WntEjVPRvijzVcDqLyf3WuohRG4gEdmc3WW6yJPLiibchXA9IUb04arg8QPt1PiNtyqYmmloziooMQ9UJ

# SERVER CONFIG
server:
  address: localhost
  port: 8080

spring:
  # DB CONNECTION
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wanted?serverTimezone=Asia/Seoul
    username: root
    password: 1026baby

  # JPA
  jpa:
    hibernate:
      # ONLY FOR DEV, LOCAL
      # ddl-auto: create, update
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true


# LOGGING LEVEL
logging:
  level:
    org:
      springframework:
        security:
          crypto:
            password: WARN
      hibernate: info
