spring:
  .datasource:
    .url = spring.datasource.url=jdbc:mysql://localhost:3306/[DB????]?autoReconnect=true
    .username=[DB??Id]
    .password=[DB??Password]
    .driver-class-name=com.mysql.jdbc.Driver